### ISSUE TITLE
初期起動時に出てくる【Firefox のプライバシーに関する通知】の変更

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/flast-gecko#2]
初期起動時に出てくる【Firefox のプライバシーに関する通知】を独自のものに変更するか、開かれない用に変更をしたほうが良いかと思われます。

使用バイナリ
https://s.0u0.biz/api/v4/files/kygwbof1njd6mp8kn8fg1mm6ia?download=1

使用環境
64bit archlinux

**Comment by mineyoshikawasnow** [comment]
fascodeのものにしました。
